// =============================================================================
// scripts/smoke-approval.ts — Day 10 Patch Proposal approval smoke test
//
// Tests the full approval flow WITHOUT real LLM API calls.
// Uses a MockProvider that returns a fixed PatchProposal JSON so the
// CoderAgent parses it and Kernel sets the task to WAITING_APPROVAL.
//
// Covers:
//   · Approve path  — file is written to workspace after approval
//   · Reject path   — file is NOT written, rejectReason is stored
//
// Run: pnpm tsx scripts/smoke-approval.ts
// No API key required.
// =============================================================================

import { Kernel, loadKernelConfig } from "../packages/core/src/index.js"
import { TaskStatus }               from "../packages/memory/src/types.js"
import { AgentType }                from "../packages/agent/src/types.js"
import {
  ProviderName,
} from "../packages/provider/src/types.js"
import type {
  IProvider,
  CompletionRequest,
  CompletionResponse,
  CostEstimate,
  ModelConfig,
  StreamChunk,
} from "../packages/provider/src/types.js"
import { existsSync, rmSync } from "node:fs"
import { join }               from "node:path"

// ---------------------------------------------------------------------------
// Assertion helpers
// ---------------------------------------------------------------------------

let passed = 0
let failed = 0

function pass(label: string): void {
  passed++
  console.log(`  ✓  ${label}`)
}

function fail(label: string, detail = ""): void {
  failed++
  console.error(`  ✗  ${label}${detail ? `\n       ${detail}` : ""}`)
}

function assert(condition: boolean, label: string, detail = ""): void {
  if (condition) pass(label)
  else           fail(label, detail)
}

const sleep = (ms: number): Promise<void> =>
  new Promise(resolve => setTimeout(resolve, ms))

async function pollUntilNotRunning(
  kernel: Kernel,
  taskId: string,
  timeoutMs = 10_000,
): Promise<string> {
  const deadline = Date.now() + timeoutMs
  while (Date.now() < deadline) {
    const detail = await kernel.getTaskDetail(taskId)
    if (
      detail.status !== TaskStatus.Running  &&
      detail.status !== TaskStatus.Pending
    ) return detail.status
    await sleep(100)
  }
  throw new Error(`Task ${taskId} did not settle within ${timeoutMs}ms`)
}

// ---------------------------------------------------------------------------
// MockProvider — returns a fixed PatchProposal JSON without any API call
// ---------------------------------------------------------------------------

const MOCK_MODEL_ID = "mock-model-v1"

const MOCK_PATCH_CONTENT = "// Generated by MockProvider\nexport const greeting = 'Hello, Hermes!';\n"

const MOCK_RESPONSE_JSON = JSON.stringify({
  summary: "Add greeting.ts module",
  patches: [
    { path: "src/greeting.ts", content: MOCK_PATCH_CONTENT },
  ],
})

class MockProvider implements IProvider {
  readonly name   = ProviderName.Anthropic
  readonly models: readonly ModelConfig[] = [
    {
      id:              MOCK_MODEL_ID,
      provider:        ProviderName.Anthropic,
      inputPer1mUsd:   0,
      outputPer1mUsd:  0,
      contextWindow:   100_000,
    },
  ]

  healthCheck(): Promise<boolean> { return Promise.resolve(true) }

  estimateCost(_req: CompletionRequest): CostEstimate {
    return {
      inputTokens:            0,
      estimatedOutputTokens:  0,
      inputCostUsd:           0,
      estimatedOutputCostUsd: 0,
      totalEstimatedUsd:      0,
    }
  }

  complete(_req: CompletionRequest): Promise<CompletionResponse> {
    return Promise.resolve({
      content:    MOCK_RESPONSE_JSON,
      usage:      { inputTokens: 10, outputTokens: 40, cacheReadTokens: 0, cacheWriteTokens: 0 },
      model:      MOCK_MODEL_ID,
      stopReason: "end_turn" as const,
    })
  }

  // Stream is not used by BaseAgent in v0.1 — stub is sufficient
  async *stream(_req: CompletionRequest): AsyncIterable<StreamChunk> {
    // no-op
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("\n══════════════════════════════════════════════════════")
  console.log("  Hermes v0.1 — Patch Approval Smoke Test")
  console.log("══════════════════════════════════════════════════════\n")

  const ROOT      = process.env["HERMES_ROOT"] ?? process.cwd()
  const APPROVE_WS = "smoke-approve-test"
  const REJECT_WS  = "smoke-reject-test"

  // Clean up from prior runs
  for (const ws of [APPROVE_WS, REJECT_WS]) {
    const p = join(ROOT, "projects", ws)
    if (existsSync(p)) rmSync(p, { recursive: true, force: true })
  }

  const config = loadKernelConfig(ROOT)

  // ═══════════════════════════════════════════════════════════════════════════
  // FLOW 1: Approve path
  // ═══════════════════════════════════════════════════════════════════════════
  console.log("─── Flow 1: Approve path ──────────────────────────────────────\n")

  const kernelA = new Kernel(config, new MockProvider())

  // 1a. Submit a Coder task
  const submitA = await kernelA.submit({
    workspace:   APPROVE_WS,
    instruction: "Add a greeting module",
    agentType:   AgentType.Coder,
  })
  assert(submitA.status === TaskStatus.Pending, "submit() returns PENDING")
  console.log(`  taskId: ${submitA.taskId}`)

  // 1b. Wait for WAITING_APPROVAL (MockProvider returns immediately)
  const statusA = await pollUntilNotRunning(kernelA, submitA.taskId)
  assert(
    statusA === TaskStatus.WaitingApproval,
    `task reaches WAITING_APPROVAL (got: "${statusA}")`,
  )

  // 1c. Inspect detail — patchProposal should be present
  const detailA = await kernelA.getTaskDetail(submitA.taskId)
  assert(
    detailA.patchProposal !== undefined,
    "getTaskDetail() returns patchProposal",
  )
  assert(
    detailA.patchProposal?.patches.length === 1,
    `patchProposal has 1 patch (got ${detailA.patchProposal?.patches.length ?? 0})`,
  )
  assert(
    detailA.patchProposal?.summary === "Add greeting.ts module",
    `patchProposal.summary matches (got: "${detailA.patchProposal?.summary ?? ""}")`,
  )

  // 1d. File must NOT exist yet
  const targetFileA = join(ROOT, "projects", APPROVE_WS, "src", "greeting.ts")
  assert(!existsSync(targetFileA), "file does NOT exist before approval")

  // 1e. approveTask — applies patch to workspace
  await kernelA.approveTask(submitA.taskId)

  // 1f. Status must be DONE
  const afterApproveA = await kernelA.getTaskDetail(submitA.taskId)
  assert(
    afterApproveA.status === TaskStatus.Done,
    `status is DONE after approveTask() (got: "${afterApproveA.status}")`,
  )

  // 1g. File must now exist with correct content
  assert(existsSync(targetFileA), "file EXISTS after approval")
  const { readFileSync } = await import("node:fs")
  const writtenContent = readFileSync(targetFileA, "utf8")
  assert(
    writtenContent === MOCK_PATCH_CONTENT,
    "written file content matches MockProvider patch",
  )

  // 1h. Cannot approve twice
  let approveAgainThrew = false
  try { await kernelA.approveTask(submitA.taskId) } catch { approveAgainThrew = true }
  assert(approveAgainThrew, "approveTask() on Done task throws")

  await kernelA.shutdown()
  console.log(`\n  Flow 1 complete — file written to: ${targetFileA}`)

  // ═══════════════════════════════════════════════════════════════════════════
  // FLOW 2: Reject path
  // ═══════════════════════════════════════════════════════════════════════════
  console.log("\n─── Flow 2: Reject path ───────────────────────────────────────\n")

  const kernelR = new Kernel(config, new MockProvider())

  // 2a. Submit
  const submitR = await kernelR.submit({
    workspace:   REJECT_WS,
    instruction: "Add a greeting module (will be rejected)",
    agentType:   AgentType.Coder,
  })
  assert(submitR.status === TaskStatus.Pending, "submit() returns PENDING")
  console.log(`  taskId: ${submitR.taskId}`)

  // 2b. Wait for WAITING_APPROVAL
  const statusR = await pollUntilNotRunning(kernelR, submitR.taskId)
  assert(
    statusR === TaskStatus.WaitingApproval,
    `task reaches WAITING_APPROVAL (got: "${statusR}")`,
  )

  // 2c. File must NOT exist
  const targetFileR = join(ROOT, "projects", REJECT_WS, "src", "greeting.ts")
  assert(!existsSync(targetFileR), "file does NOT exist before reject")

  // 2d. rejectTask
  await kernelR.rejectTask(submitR.taskId, "The code style does not meet our standards.")

  // 2e. Status must be FAILED
  const afterRejectR = await kernelR.getTaskDetail(submitR.taskId)
  assert(
    afterRejectR.status === TaskStatus.Failed,
    `status is FAILED after rejectTask() (got: "${afterRejectR.status}")`,
  )

  // 2f. rejectReason stored
  assert(
    afterRejectR.rejectReason === "The code style does not meet our standards.",
    `rejectReason stored correctly (got: "${afterRejectR.rejectReason ?? ""}")`,
  )

  // 2g. File must NOT have been written
  assert(!existsSync(targetFileR), "file does NOT exist after rejection")

  // 2h. Cannot reject twice
  let rejectAgainThrew = false
  try { await kernelR.rejectTask(submitR.taskId) } catch { rejectAgainThrew = true }
  assert(rejectAgainThrew, "rejectTask() on Failed task throws")

  await kernelR.shutdown()

  // ── Clean up ──────────────────────────────────────────────────────────────
  for (const ws of [APPROVE_WS, REJECT_WS]) {
    const p = join(ROOT, "projects", ws)
    if (existsSync(p)) rmSync(p, { recursive: true, force: true })
  }

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log(`\n══════════════════════════════════════════════════════`)
  console.log(`  Results: ${passed} passed, ${failed} failed`)
  console.log(`══════════════════════════════════════════════════════\n`)

  if (failed > 0) process.exit(1)
}

main().catch(err => {
  console.error("\nUnhandled error:", err)
  process.exit(1)
})
